//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student2
    {
        public int StdId { get; set; }
        public string StdName { get; set; }
        public long StdPh { get; set; }
        public string StdAdd { get; set; }
    }
}
